### ISSUE TITLE
Download JAR for the Eclipse CDT Core. [org.eclipse.cdt.core]

### ISSUE THREAD

**Issue by VenoVeno** [eclipse-cdt/cdt#276]
Hi,
    I'm building this eclipse cdt as a standalone project for parsing and analysing AST.
Can you add latest JAR for the source code.

**Comment by jonahgraham** [comment]
Hi @VenoVeno, all the downloads we make available are listed/linked from https://github.com/eclipse-cdt/cdt#download. If you need the latest and greatest unreleased code pre-built, you can get it also. Details on https://github.com/eclipse-cdt/cdt/blob/main/Downloads.md#development-builds (which is linked from the first one, just wanted to make sure you saw it)

**Comment by VenoVeno** [comment]
Hi @jonahgraham,

Just to confirm, i need latest `org.eclipse.cdt.core.jar` for the Standalone project [CDT Version 11]. 
I found the Jar in the Eclipse Jenkins build, [link](https://ci.eclipse.org/cdt/job/cdt/job/main/lastSuccessfulBuild/artifact/releng/org.eclipse.cdt.repo/target/repository/plugins/#:~:text=org.eclipse.cdt.core_8.1.0.202302041455.jar), but it is referring to the `8.1.0.202302041455.jar`, but the latest CDT version is 11_0_0. 

_Is the version difference intentional?_ 

If the latest jar is not updated, where can i download the latest `org.eclipse.cdt.core.jar` for the CDT Version 11_0_0. I also checked the CDT_11_0 branch in Jenkins [link](https://ci.eclipse.org/cdt/job/cdt/job/cdt_11_0/lastSuccessfulBuild/artifact/releng/org.eclipse.cdt.repo/target/repository/plugins/#:~:text=org.eclipse.cdt.core_8.0.0.202211292120.jar), it is referring to `8.0.0.202211292120.jar`.

**Comment by jonahgraham** [comment]
> _Is the version difference intentional?_

Yes, current main branch is 11.1.0, so new minor API is allowed since 11.0.0 release.

https://github.com/eclipse-cdt/cdt#download link is for most users, you probably want the extra details in the release page https://github.com/eclipse-cdt/cdt/releases/tag/CDT_11_0_0 Specifically, the p2 site you want to install from is https://download.eclipse.org/tools/cdt/releases/11.0, or if you want to lock it down to 11.0.0, then https://download.eclipse.org/tools/cdt/releases/11.0/cdt-11.0.0/ will do it.

**Comment by VenoVeno** [comment]
Thanks for your comment.
