### ISSUE TITLE
CCorePlugin.log(IStatus) fails with NullPointerException

### ISSUE THREAD

**Issue by max-leuthaeuser** [eclipse-cdt/cdt#957]
**Describe the bug**
When using CDT standalone (via its API in a project outside the Eclipse runtime) `CCorePlugin.log(IStatus)` fails with a `NullPointerException` because `CCorePlugin.getDefault()` returns null.

Many things are logged via `CCorePlugin.log(IStatus)` (https://github.com/eclipse-cdt/cdt/blob/main/core/org.eclipse.cdt.core/src/org/eclipse/cdt/core/CCorePlugin.java#L1611).
E.g. during the ambiguity resolving (https://github.com/eclipse-cdt/cdt/blob/main/core/org.eclipse.cdt.core/parser/org/eclipse/cdt/internal/core/dom/parser/ASTAmbiguousNode.java#L166).

Is there a way to disable that logging so one does not rely on `CCorePlugin` anymore?
Or can this behavior be replaced/changed via API?

**Version Information:**
 - CDT Version: 8.5.0.202410191453

**Comment by jonahgraham** [comment]
@max-leuthaeuser the CDT generally hasn't been written to run without an OSGi runtime. I would be happy to review PRs that resolve this particular NPE (i.e. have some fallback code for null `getDefault()`) - but I don't know how long until you run into the next problem of no OSGi runtime or otherwise unmet dependencies of the bundle: https://github.com/eclipse-cdt/cdt/blob/9e9be4a5e276e0e3104811f159ed68d0e7982c8b/core/org.eclipse.cdt.core/META-INF/MANIFEST.MF#L134-L146
